version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - ./media:/media:ro
      - jellysentia-plugin:/config/plugins/JellySentia
    ports:
      - "8096:8096"
    restart: unless-stopped
    depends_on:
      - analysis-core
    networks:
      - jellysentia-network

  analysis-core:
    build:
      context: ..
      dockerfile: docker/Dockerfile.analysis
    container_name: jellysentia-analysis
    environment:
      - GRPC_PORT=50051
      - ESSENTIA_THREADS=4
      - FAISS_INDEX_PATH=/data/index
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/data
      - ./media:/media:ro
      - analysis-cache:/cache
    ports:
      - "50051:50051"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "localhost:50051", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jellysentia-network

  plugin:
    build:
      context: ..
      dockerfile: docker/Dockerfile.plugin
    container_name: jellysentia-plugin
    environment:
      - JELLYFIN_URL=http://jellyfin:8096
      - ANALYSIS_SERVICE_URL=analysis-core:50051
      - DATABASE_PATH=/data/jellysentia.db
    volumes:
      - jellysentia-plugin:/plugin
      - ./data:/data
    depends_on:
      - jellyfin
      - analysis-core
    restart: unless-stopped
    networks:
      - jellysentia-network

  webui:
    image: nginx:alpine
    container_name: jellysentia-webui
    volumes:
      - ../webui/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8097:80"
    restart: unless-stopped
    networks:
      - jellysentia-network

volumes:
  jellysentia-plugin:
  analysis-cache:

networks:
  jellysentia-network:
    driver: bridge