name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-plugin:
    name: Test Plugin
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: |
        cd plugin/jellyfin
        dotnet restore
    
    - name: Build
      run: |
        cd plugin/jellyfin
        dotnet build --no-restore
    
    - name: Test
      run: |
        cd plugin/jellyfin
        dotnet test --no-build --verbosity normal

  test-analysis-core:
    name: Test Analysis Core
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfftw3-dev libavcodec-dev libavformat-dev
    
    - name: Install Python dependencies
      run: |
        cd analysis-core
        pip install -r server/requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        cd tests
        pytest unit/test_analysis.py -v --cov=analysis_core
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  test-webui:
    name: Test Web UI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd webui
        npm ci
    
    - name: Lint
      run: |
        cd webui
        npm run lint
    
    - name: Build
      run: |
        cd webui
        npm run build
    
    - name: Test
      run: |
        cd webui
        npm test

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Analysis Core Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.analysis
        push: false
        tags: jellysentia/analysis:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Plugin Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.plugin
        push: false
        tags: jellysentia/plugin:test

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test-plugin, test-analysis-core, docker-build]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run integration tests
      run: |
        docker-compose -f docker-compose.test.yml up --abort-on-container-exit